components:
  assisted_service: false
  cluster_api: false
  cluster_api_provider_metal3: false
  cluster_api_provider_openshift_assisted: false
  cluster_lifecycle: false
  cluster_manager: true
  cluster_proxy_addon: false
  console_mce: false
  discovery: false
  hive: false
  hypershift: false
  hypershift_local_hosting: false
  image_based_install_operator_preview: false
  local_cluster: false
  managedserviceaccount: false
  server_foundation: false
external_components: []
operand_images:
  addon_manager: "quay.io/stolostron/addon-manager@sha256:caf5ffd4eca56c5741e638f800964d3da4ff4dd9fd01ac991a78462e6a010220"
  apiserver_network_proxy: "quay.io/stolostron/apiserver-network-proxy@sha256:dc74c7c67ca851f50b83d7a03f91d028214fd8a941f12edd4411b860dc7b763d"
  assisted_image_service: "quay.io/stolostron/assisted-image-service@sha256:b58891c3de0a63e5b53238a78f71c2461256a9bff73971e0e9553bddb8c71853"
  assisted_installer_agent: "quay.io/stolostron/assisted-installer-agent@sha256:a9b31ab5e41986ecf464613d285e9bd7c5518b94e238f6da5c8d8fabd03742a6"
  assisted_installer_controller: "quay.io/stolostron/assisted-installer-controller@sha256:b8cbd23e4615d6dc60d4701d947c9bd154bb57abd046f9c528bfad28c815fca5"
  assisted_installer: "quay.io/stolostron/assisted-installer@sha256:ad8626590a8178611aca379f9396f3606bf16a91780d103938c1606a6bf81f71"
  assisted_service_8: "quay.io/stolostron/assisted-service-el8@sha256:8a817c1d79fa6afd88c82ad0c7ef82501dc8080cbca85452e405a38913d7628d"
  assisted_service_9: "quay.io/stolostron/assisted-service@sha256:c45eea08d53967de089567dac526ad694f424b50bee4ceb107a306953c050a55"
  aws_encryption_provider: "quay.io/stolostron/aws-encryption-provider@sha256:83f11e28004fcbb31d7ec6c34ef2d2ec7dd8fc175c5e0135f6ace9894c65bfd0"
  backplane_must_gather: "quay.io/stolostron/backplane-must-gather@sha256:72c5ae6e669a1b90699644e1cd5283bbaffe8372cc83fdfb0c646a93aaaae1ab"
  backplane_operator: "quay.io/stolostron/backplane-operator@sha256:c7567d9d0da279f6616b95ce9d130dfcdae073c04c598f2f3e112f73dae8b820"
  backplane_operator_test: "quay.io/stolostron/backplane-operator-test@sha256:fd0a645124a8ca6588df9b0d588316aa232a5d02902823127ebf7f278c870043"
  cluster_api_provider_agent: "quay.io/stolostron/cluster-api-provider-agent@sha256:e2b52112f6ae5f16b8349cb80b244c739e5ac1bd41872d08379698a04c78a0d8"
  cluster_api_provider_aws: "quay.io/stolostron/cluster-api-aws-controller@sha256:22a57cf5b74d0692025f0b0f57c5f28f8b492ea13295e9101b63f57766ffff38"
  cluster_api_provider_azure: "quay.io/stolostron/cluster-api-provider-azure@sha256:f6e780adc1bf3fe64303fcb8c5d080ab639e62c62d0577a1bbae5b5f5bfa393d"
  cluster_api_provider_kubevirt: "quay.io/stolostron/cluster-api-provider-kubevirt@sha256:44f8bb72b975456d4151a88a560fc525ad6f4da7968a38e94a86b6dd77d3c543"
  cluster_api_provider_openshift_assisted_bootstrap: "quay.io/stolostron/cluster-api-provider-openshift-assisted-bootstrap@sha256:f34471944a9535672ea97eeb2e73cb3c48583de6819a025c5c7aff3384a82755"
  cluster_api_provider_openshift_assisted_control_plane: "quay.io/stolostron/cluster-api-provider-openshift-assisted-control-plane@sha256:6a74882c85b782f099eda7bd23344330a8899a7f9cb354a71fec41a5209478be"
  cluster_api: "quay.io/stolostron/cluster-api@sha256:7a04ac4e5bdaf29498af75b2b7c4ff19cb6223f2076c9373a3a955553243ddda"
  clusterclaims_controller: "quay.io/stolostron/clusterclaims-controller@sha256:8a3945e3127328e6f20fab5e250f320e27c0f517e564838c7bb83a50b59ac019"
  cluster_curator_controller: "quay.io/stolostron/cluster-curator-controller@sha256:c97ad90fd198b234301b367bc48c2b690562711f3f0ecfa14388169b28f7b424"
  cluster_image_set_controller: "quay.io/stolostron/cluster-image-set-controller@sha256:2cea7a3dadb3f58671411ef110de3c276edd99e9ad5f794fb492cdbd89cae676"
  clusterlifecycle_state_metrics: "quay.io/stolostron/clusterlifecycle-state-metrics@sha256:f50790d626b67ba32b2e8f47ba75d6895a54a24c7e27ede016f449aca3c05e3f"
  cluster_proxy_addon: "quay.io/stolostron/cluster-proxy-addon@sha256:674abd3cf9b3b953a4103d5c1ced32d65e70e17fc200a63c7cc65bcfb4e662c4"
  cluster_proxy: "quay.io/stolostron/cluster-proxy@sha256:1fc3e70e679a052d4fe1a50f268e6b3ef5a8fc17102df2edc5e38ba714aa194a"
  console_mce: "quay.io/stolostron/console-mce@sha256:cf3111376c5f337a1b167b48fb5c9eb7e96528edffded6614bd4070e85dd0910"
  discovery_operator: "quay.io/stolostron/discovery-operator@sha256:e6eb524c1208ab40cb0b5201a3ba4135330de91f918a76ccc3ac3693d6851122"
  discovery_operator_tests: "quay.io/stolostron/discovery-operator-tests@sha256:12617e4bef1b742b061f9a3223fcf8e9458b817467f0d551c421d14e5dab3111"
  discovery_testserver: "quay.io/stolostron/discovery-testserver@sha256:fea15ba83dd90d4f7b71fa248319cd902b967e8e140ab7b25090c6459f1b77e1"
  foundation_e2e: "quay.io/stolostron/foundation-e2e@sha256:b5502848bee71b7fb9f4b1a54f00ccbdf77a9ecbb5e3e7bfad815057f2c55e2f"
  helloprow_go: "quay.io/stolostron/helloprow-go@sha256:e055ab3773a248c22dbde9847a3289e8512ccc85c6e9015544fc4f59d14b9cad"
  helloworld: "quay.io/stolostron/helloworld@sha256:a790795409f6e781f506b6a63f39f7d344f01efa30c3de87b1727dc2010d5bbf"
  hypershift_addon_operator_canary_test: "quay.io/stolostron/hypershift-addon-operator-canary-test@sha256:23688632b790d8961c2ef8ee2b1dd262e9d965a0a38b8b6eaa43851ecc4e75c1"
  hypershift_addon_operator: "quay.io/stolostron/hypershift-addon-operator@sha256:3365d2315aae4cac464a8c319cc40b0b98665918be86f696e6c115767ce8f7ac"
  hypershift_operator: "quay.io/stolostron/hypershift-operator@sha256:cc84043bbe37bfcb5aabc8d31b29523231fb94488d6d8692f5de5acf137c7534"
  image_based_install_operator: "quay.io/stolostron/image-based-install-operator@sha256:3470a53cb5f337f8450109237961c258d7ad6f516313b88edf131c6797756161"
  ip_address_manager: "quay.io/stolostron/ip-address-manager@sha256:6f06170c1684fdd234ef8edbb65b73b47affbec609800493d427d5169b7dfe22"
  kube_rbac_proxy_mce: "quay.io/stolostron/kube-rbac-proxy-mce@sha256:365124bd4e035bb8b7b6b2c6bbb861f69a25a5217b03e8d120cd717e9fe18822"
  managedcluster_import_controller: "quay.io/stolostron/managedcluster-import-controller@sha256:64ee526629b3605f7819c74cad14951293d1b47b93dfa7188c8149fde6ad6323"
  managed_serviceaccount_e2e: "quay.io/stolostron/managed-serviceaccount-e2e@sha256:e983d2cd7f240dbbe47612055185873ffa63e5ac34083732557cdf2c20bc8a1a"
  managed_serviceaccount: "quay.io/stolostron/managed-serviceaccount@sha256:cefa8932e31bad17ed0c7ee739f024dd94681887c704ca8275c44c710cb4b19a"
  multicloud_manager: "quay.io/stolostron/multicloud-manager@sha256:c5d5d50c30d374fdfc43902b640c543ef2cdeb24a1420e2c9f870ee5882beaeb"
  openshift_hive: "quay.io/stolostron/hive@sha256:86ff94d3e7c174ac4d6818183c66791edc7638965dd09e2d41172609c81f451f"
  ose_aws_cluster_api_controllers_rhel9: "quay.io/stolostron/ose_aws_cluster_api_controllers_rhel9@sha256:5bdd5905d5a6c6a611df6bf0aa0caf22eb768c938b52ae6a733ed5277c6e1c22"
  ose_baremetal_cluster_api_controllers_rhel9: "quay.io/stolostron/ose-baremetal-cluster-api-controllers-rhel9@sha256:6f06170c1684fdd234ef8edbb65b73b47affbec609800493d427d5169b7dfe22"
  ose_cluster_api_rhel9: "quay.io/stolostron/ose_cluster_api_rhel9@sha256:5bdd5905d5a6c6a611df6bf0aa0caf22eb768c938b52ae6a733ed5277c6e1c22"
  placement: "quay.io/stolostron/placement@sha256:a8fb096766163bc45943de998cf57293f61eab3ab4e14730e030ebd2414c1e72"
  postgresql_12: "quay.io/stolostron/postgresql-12-centos7@sha256:94727d70e0afbf4e167e078744f3a10ac9d82edc553d57b0ecbb5443264f07e1"
  provider_credential_controller: "quay.io/stolostron/provider-credential-controller@sha256:637248347de70b1debe011816cdbd171d09f9a86fc61b31e316827900c3d4697"
  registration_operator: "quay.io/stolostron/registration-operator@sha256:c97d1d29844dc0aac68de600a19c6c9006cbabea64b9a3f06218d3f07573eb13"
  registration: "quay.io/stolostron/registration@sha256:d1ae6c40d32a504c2405258a2b2b47bf82a60c63c7995c7d5710ed01ab23c82f"
  work: "quay.io/stolostron/work@sha256:8be6b402cdad32c05669bed7ee5cd3f3a17edbfb94770e7b6a0a46c625d521ec"
operator_image: "quay.io/stolostron/backplane-operator@sha256:c7567d9d0da279f6616b95ce9d130dfcdae073c04c598f2f3e112f73dae8b820"
operator_version: 2.10.0
pull_secret: "e30K"
