components:
  assisted_service: true
  cluster_api: false
  cluster_api_provider_metal3_preview: false
  cluster_api_provider_openshift_assisted_preview: true
  cluster_lifecycle: false
  cluster_manager: true
  cluster_proxy_addon: false
  console_mce: false
  discovery: false
  hive: false
  hypershift: false
  hypershift_local_hosting: false
  image_based_install_operator_preview: false
  local_cluster: false
  managedserviceaccount: false
  server_foundation: false
external_components: []
operand_images:
  addon_manager: "quay.io/stolostron/addon-manager@sha256:1ddca7721efbe57c700e51785909872941f73eb0b5eeea1d10dec6320dad037a"
  apiserver_network_proxy: "quay.io/stolostron/apiserver-network-proxy@sha256:dc74c7c67ca851f50b83d7a03f91d028214fd8a941f12edd4411b860dc7b763d"
  assisted_image_service: "quay.io/stolostron/assisted-image-service@sha256:185b462744fb9d3b2c0a01eda4e9ff4f3f5e5be9c50fe251d14ed4151c6213f3"
  assisted_installer_agent: "quay.io/stolostron/assisted-installer-agent@sha256:2387d0d7d6daa70fd1b3555e61b4c1d032a20a7ae31693aaded3f2d476c58558"
  assisted_installer_controller: "quay.io/stolostron/assisted-installer-controller@sha256:5a0e8b6978efa8b3b86d751356e13b5df494caa831b11d73044c87779fb0aa07"
  assisted_installer: "quay.io/stolostron/assisted-installer@sha256:a5a3fa64950f288e3fcf343516f10e1fc60a533ef875f82d5c8ffd18942254f3"
  assisted_service_8: "quay.io/stolostron/assisted-service-el8@sha256:6a273342df95d2f36d4396e4b8ad1ded097753fcf3e590e5b73703a4890235ec"
  assisted_service_9: "quay.io/stolostron/assisted-service@sha256:13f5cf27e99c3f7fa271896cbd1ce715ca38b6fa2a057f4cf0baee8cdff4fe82"
  aws_encryption_provider: "quay.io/stolostron/aws-encryption-provider@sha256:83f11e28004fcbb31d7ec6c34ef2d2ec7dd8fc175c5e0135f6ace9894c65bfd0"
  backplane_must_gather: "quay.io/stolostron/backplane-must-gather@sha256:266976d494932c89148ed5b1a55c13a6291b4b71582e8cebb8847ee0714720a3"
  backplane_operator: "quay.io/stolostron/backplane-operator@sha256:ae28e85a3defb993a7943bf40e48b4f4e0941c10b14a0537915df35e40ff62d7"
  backplane_operator_test: "quay.io/stolostron/backplane-operator-test@sha256:15523634577153862f9a891a78eb4f9d0b37f29efdb94a29aaef827243d80f19"
  cluster_api_provider_agent: "quay.io/stolostron/cluster-api-provider-agent@sha256:1ed9bb50cc94bb2e1d653fa5dc0ac569bed34c910146f78a93a1746427ac1ff1"
  cluster_api_provider_aws: "quay.io/stolostron/cluster-api-aws-controller@sha256:22a57cf5b74d0692025f0b0f57c5f28f8b492ea13295e9101b63f57766ffff38"
  cluster_api_provider_azure: "quay.io/stolostron/cluster-api-provider-azure@sha256:f6e780adc1bf3fe64303fcb8c5d080ab639e62c62d0577a1bbae5b5f5bfa393d"
  cluster_api_provider_kubevirt: "quay.io/stolostron/cluster-api-provider-kubevirt@sha256:44f8bb72b975456d4151a88a560fc525ad6f4da7968a38e94a86b6dd77d3c543"
  cluster_api_provider_openshift_assisted_bootstrap: "quay.io/stolostron/cluster-api-provider-openshift-assisted-bootstrap@sha256:6f06170c1684fdd234ef8edbb65b73b47affbec609800493d427d5169b7dfe22"
  cluster_api_provider_openshift_assisted_control_plane: "quay.io/stolostron/cluster-api-provider-openshift-assisted-control-plane@sha256:6f06170c1684fdd234ef8edbb65b73b47affbec609800493d427d5169b7dfe22"
  cluster_api: "quay.io/stolostron/cluster-api@sha256:7a04ac4e5bdaf29498af75b2b7c4ff19cb6223f2076c9373a3a955553243ddda"
  clusterclaims_controller: "quay.io/stolostron/clusterclaims-controller@sha256:5584d1e06dcfff88e844a9dd99ff08c34e096bb2de35093e01bd776059f33248"
  cluster_curator_controller: "quay.io/stolostron/cluster-curator-controller@sha256:2d8221f2a8a87c822f422100d4db957f8af674cccad86a4fb6d32d318be754c5"
  cluster_image_set_controller: "quay.io/stolostron/cluster-image-set-controller@sha256:cc7ce94ee88ca53621a3dbb8cd2b627fe0da3a62eb11da228a7adf7d13cade7e"
  clusterlifecycle_state_metrics: "quay.io/stolostron/clusterlifecycle-state-metrics@sha256:f26910342d785edc8dd92b8a488ad65e81058a55189d880c21f6f54145c50282"
  cluster_proxy_addon: "quay.io/stolostron/cluster-proxy-addon@sha256:d6a67bb9b49fd8b083280da708b9d9f7a16518264f255ff22b48522a90c84649"
  cluster_proxy: "quay.io/stolostron/cluster-proxy@sha256:ef0379bef545b4923c636fceb83cf41204233a2071815f010d375236b0d3ff00"
  console_mce: "quay.io/stolostron/console-mce@sha256:51f382ff9eb556fb618e57673f3192ddd95e52f525de3b6ac0edbffb92eb15a4"
  discovery_operator: "quay.io/stolostron/discovery-operator@sha256:fba26e97d7d8156f4586b67e3743b1bacb1e6a2bd0976628c1fe38596f42f587"
  discovery_operator_tests: "quay.io/stolostron/discovery-operator-tests@sha256:f11a1e89c3c5633c70d1059ff4b9f16230426caf328798dc6d2282ea6b523605"
  discovery_testserver: "quay.io/stolostron/discovery-testserver@sha256:893a321d2d3066e3e9c19fd30bd3949b2d53ec3ec7ec29a04bc528c6aa2ab276"
  foundation_e2e: "quay.io/stolostron/foundation-e2e@sha256:b5502848bee71b7fb9f4b1a54f00ccbdf77a9ecbb5e3e7bfad815057f2c55e2f"
  helloprow_go: "quay.io/stolostron/helloprow-go@sha256:e055ab3773a248c22dbde9847a3289e8512ccc85c6e9015544fc4f59d14b9cad"
  helloworld: "quay.io/stolostron/helloworld@sha256:a790795409f6e781f506b6a63f39f7d344f01efa30c3de87b1727dc2010d5bbf"
  hypershift_addon_operator_canary_test: "quay.io/stolostron/hypershift-addon-operator-canary-test@sha256:3342fbe8fdb71cdb14e06a4a7c107cad8a2050fd6b4a442281dffc7402d5f7ca"
  hypershift_addon_operator: "quay.io/stolostron/hypershift-addon-operator@sha256:708b9460c10ccdb8b1fab48b44817659e7ac9b1c7c71a3ab9376e14db3fffa97"
  hypershift_operator: "quay.io/stolostron/hypershift-operator@sha256:cc84043bbe37bfcb5aabc8d31b29523231fb94488d6d8692f5de5acf137c7534"
  image_based_install_operator: "quay.io/stolostron/image-based-install-operator@sha256:8cc89bdefba39222a0c82199c6ca3115626966ec8d0a8706e61c092d47952698"
  ip_address_manager: "quay.io/stolostron/ip-address-manager@sha256:6f06170c1684fdd234ef8edbb65b73b47affbec609800493d427d5169b7dfe22"
  kube_rbac_proxy_mce: "quay.io/stolostron/kube-rbac-proxy-mce@sha256:b1abb4206dc3eb80040ffc7c00fee7694a363b05537a0b82036d37821c7eb97a"
  managedcluster_import_controller: "quay.io/stolostron/managedcluster-import-controller@sha256:04c09891c5351d6496bc13f2b0e1d73e8b45cf9935bcc50097d9d501b63bfbff"
  managed_serviceaccount_e2e: "quay.io/stolostron/managed-serviceaccount-e2e@sha256:e983d2cd7f240dbbe47612055185873ffa63e5ac34083732557cdf2c20bc8a1a"
  managed_serviceaccount: "quay.io/stolostron/managed-serviceaccount@sha256:7e240e2a89944833d27e1c4a2ed9fb2e4820b57209acc240c805372c38318d68"
  multicloud_manager: "quay.io/stolostron/multicloud-manager@sha256:5663f9a0a1ae5dc48a27507d9dce6b95a256b55e42d3ba2d56f8e4f44ea638db"
  openshift_hive: "quay.io/stolostron/hive@sha256:86ff94d3e7c174ac4d6818183c66791edc7638965dd09e2d41172609c81f451f"
  ose_aws_cluster_api_controllers_rhel9: "quay.io/stolostron/ose_aws_cluster_api_controllers_rhel9@sha256:5bdd5905d5a6c6a611df6bf0aa0caf22eb768c938b52ae6a733ed5277c6e1c22"
  ose_baremetal_cluster_api_controllers_rhel9: "quay.io/stolostron/ose-baremetal-cluster-api-controllers-rhel9@sha256:6f06170c1684fdd234ef8edbb65b73b47affbec609800493d427d5169b7dfe22"
  ose_cluster_api_rhel9: "quay.io/stolostron/ose_cluster_api_rhel9@sha256:5bdd5905d5a6c6a611df6bf0aa0caf22eb768c938b52ae6a733ed5277c6e1c22"
  placement: "quay.io/stolostron/placement@sha256:a8fb096766163bc45943de998cf57293f61eab3ab4e14730e030ebd2414c1e72"
  postgresql_12: "quay.io/stolostron/postgresql-12-centos7@sha256:94727d70e0afbf4e167e078744f3a10ac9d82edc553d57b0ecbb5443264f07e1"
  provider_credential_controller: "quay.io/stolostron/provider-credential-controller@sha256:637248347de70b1debe011816cdbd171d09f9a86fc61b31e316827900c3d4697"
  registration_operator: "quay.io/stolostron/registration-operator@sha256:c97d1d29844dc0aac68de600a19c6c9006cbabea64b9a3f06218d3f07573eb13"
  registration: "quay.io/stolostron/registration@sha256:d1ae6c40d32a504c2405258a2b2b47bf82a60c63c7995c7d5710ed01ab23c82f"
  work: "quay.io/stolostron/work@sha256:8be6b402cdad32c05669bed7ee5cd3f3a17edbfb94770e7b6a0a46c625d521ec"
operator_image: "quay.io/stolostron/backplane-operator@sha256:ae28e85a3defb993a7943bf40e48b4f4e0941c10b14a0537915df35e40ff62d7"
operator_version: 2.10.0
pull_secret: "e30K"
