apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pull_secret | quote }}
kind: Secret
metadata:
  name: open-cluster-management-image-pull-credentials
  namespace: '{{ .Release.Namespace }}'
type: kubernetes.io/dockerconfigjson
